### ISSUE TITLE
Twitch Update

### ISSUE THREAD

**Issue by DrewSunn** [ScottMellors/io.predictionbuttons.sdPlugin#2]
Twitch updated predictions to do up to 10 options in every prediction. It'd be nice to be able to do it automatically via the stream deck plug-in.

**Comment by enarkay** [comment]
+1 for this request/suggestion - I literally came to the github to request this exact feature, guess someone beat me to it lol.

**Comment by ScottMellors** [comment]
Already got the background work for this done, waiting on the Twitch API update, been waiting nearly a month for it, should be soon(tm)! 

Sorry this didn't get a reply sooner, didn't get a notification for this!

**Comment by ScottMellors** [comment]
Updated and released!

**Comment by enarkay** [comment]
> Updated and released!

Thank you so much for the update! I came as soon as I received the alert to express my gratitude :)
