### ISSUE TITLE
Issue: Not letting me add more than 4 responses?

### ISSUE THREAD

**Issue by KensonPlayz** [ScottMellors/io.predictionbuttons.sdPlugin#3]
I want to add a prediction for 5 options, but it won't let me add more than 4 for some reason.

I've tried it with numbers "1, 2, 3, 4, 5 (fail)" and "One, Two, Three, Four, Five (fail)" and neither works. Is there a bug with adding more than 4 in? I can type all 5 manually in the dashboard but not on my SD buttons.

**Comment by ScottMellors** [comment]
Hello Kenson, sorry for the slow reply, will have a peek at this and report back ASAP.

**Comment by ScottMellors** [comment]
Couldn't replicate, not heard anything, if issue persists will reopen.
